

services:
  db-auth:
    image: postgres:15-alpine 
    restart: always
    env_file:
      - ./.env.auth.db
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    networks:
      - microservice-network
  
  db-media:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env.media.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - microservice-network


  #django i am using as gateway
  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/app
    networks:
      - microservice-network
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    
    ports:
      - "8001:8001" # Host port:Container port
    # Crucial for development: Sync local code and ignore cache
    volumes:
      - ./services/auth-service:/app # Maps your local code into the container
    networks:
      - microservice-network
    
  media-service:
    build:
      context: ./services/media-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./services/media-service:/app
    networks:
      - microservice-network
        
  


networks:
  microservice-network:
    driver: bridge # This creates the shared network for inter-service communication
volumes:
  postgres_data: