version: '3.8'

services:

  #django i am using as gateway
  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/app
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    
    ports:
      - "8001:8001" # Host port:Container port
    # Crucial for development: Sync local code and ignore cache
    volumes:
      - ./services/auth-service:/app # Maps your local code into the container
      - /app/__pycache__    # Prevents local filesystem corruption from container cache
    networks:
      - microservice-network
        
  


networks:
  microservice-network:
    driver: bridge # This creates the shared network for inter-service communication

# If you want to use volumes later for a DB, also add a volumes block here