

services:
  db-auth:
    image: postgres:15-alpine 
    restart: always
    env_file:
      - ./.env.auth.db
    volumes:
    - auth_postgres_data:/var/lib/postgresql/data/
    ports:
    - "55433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_service_user -d fastapi_auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservice-network
  
  db-media:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env.media.db
    volumes:
      - media_postgres_data:/var/lib/postgresql/data/
    ports:
    - "55434:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U media_service_user -d fastapi_media_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservice-network


  #django i am using as gateway
  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/app
    networks:
      - microservice-network
    environment:
      - PYTHONUNBUFFERED=1
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    depends_on:
      db-auth:
        condition: service_healthy
    ports:
      - "8001:8001" # Host port:Container port
    # Crucial for development: Sync local code and ignore cache
    volumes:
      - ./services/auth-service:/app # Maps your local code into the container
        
    networks:
      - microservice-network
    
  media-service:
    build:
      context: ./services/media-service
      dockerfile: Dockerfile
    depends_on:
      db-media:
        condition: service_healthy
    ports:
      - "8002:8002"
    volumes:
      - ./services/media-service:/app
    networks:
      - microservice-network
        
  


networks:
  microservice-network:
    driver: bridge # This creates the shared network for inter-service communication
volumes:
  auth_postgres_data:
  media_postgres_data: